/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HealthcareSystem } from "./HealthcareSystem";
export * as factories from "./factories";
export { HealthcareSystem__factory } from "./factories/HealthcareSystem__factory";
